name: 'my_new_project'
version: '1.0.0'
require-dbt-version: [">=1.7.0", "<3.0.0"]

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  dev_start_date: '2019-01-01'
  dev_end_date: '2021-01-01'
  


models:
  my_new_project:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table

flags:
  require_generic_test_arguments_property: true